export type RuleEntry = { vi: string; kana: string[]; note?: string };

// Thick starter rules for common Vietnamese surnames & given names (tone-removed, lowercased).
// These entries override the phonology fallback and help match "real-world" spellings used in hồ sơ/dịch thuật.
// Order matters: more specific tokens first.
export const RULES: RuleEntry[] = [
  { vi: "nguyen", kana: ["グエン", "ングエン", "グェン"] },
  { vi: "tran", kana: ["チャン", "トラン"] },
  { vi: "le", kana: ["レ", "レー"] },
  { vi: "pham", kana: ["ファム", "フアム"] },
  { vi: "hoang", kana: ["ホアン", "ファン", "ホワン"] },
  { vi: "huynh", kana: ["フイン", "ヒュイン", "フュイン"] },
  { vi: "phan", kana: ["ファン", "フアン"] },
  { vi: "vu", kana: ["ヴー", "ブー"] },
  { vi: "vo", kana: ["ヴォ", "ボ"] },
  { vi: "dang", kana: ["ダン", "ザン"] },
  { vi: "bui", kana: ["ブイ", "ブーイ"] },
  { vi: "do", kana: ["ド", "ドー"] },
  { vi: "dinh", kana: ["ディン", "ジン"] },
  { vi: "ngo", kana: ["ゴ", "ンゴ"] },
  { vi: "ngoc", kana: ["ゴック", "ンゴック"] },
  { vi: "duong", kana: ["ズオン", "ドゥオン", "ズオンー"] },
  { vi: "truong", kana: ["チュオン", "チュオンー", "トゥオン"] },
  { vi: "doan", kana: ["ドアン", "トアン"] },
  { vi: "chau", kana: ["チャウ", "チョウ"] },
  { vi: "chung", kana: ["チュン", "チュング"] },
  { vi: "trieu", kana: ["チエウ", "チュウ"] },
  { vi: "vuong", kana: ["ヴオン", "ブオン"] },
  { vi: "luong", kana: ["ルオン", "リュオン"] },
  { vi: "luu", kana: ["ルー", "リュウ"] },
  { vi: "ly", kana: ["リー", "リ"] },
  { vi: "cao", kana: ["カオ"] },
  { vi: "ta", kana: ["タ"] },
  { vi: "tong", kana: ["トン"] },
  { vi: "mai", kana: ["マイ"] },
  { vi: "ha", kana: ["ハ", "ハー"] },
  { vi: "ho", kana: ["ホ", "ホー"] },
  { vi: "dao", kana: ["ダオ", "タオ"] },
  { vi: "nghia", kana: ["ギア", "ニア", "ギアー"] },
  { vi: "hieu", kana: ["ヒエウ", "ヒョウ"] },
  { vi: "khoa", kana: ["クオア", "コア", "クワ"] },
  { vi: "khoi", kana: ["コイ", "クオイ"] },
  { vi: "khai", kana: ["カイ"] },
  { vi: "khanh", kana: ["カイン", "カン"] },
  { vi: "khang", kana: ["カン", "カング"] },
  { vi: "kien", kana: ["キエン", "ケン"] },
  { vi: "kiet", kana: ["キエット", "ケット"] },
  { vi: "lam", kana: ["ラム", "ラン"] },
  { vi: "linh", kana: ["リン", "リィン"] },
  { vi: "long", kana: ["ロン", "ロング"] },
  { vi: "minh", kana: ["ミン", "ミィン"] },
  { vi: "nam", kana: ["ナム"] },
  { vi: "nhat", kana: ["ニャット", "ニャツ"] },
  { vi: "nhan", kana: ["ニャン", "ナン"] },
  { vi: "nhi", kana: ["ニー", "ニ"] },
  { vi: "thanh", kana: ["タイン", "タン", "タィン"] },
  { vi: "thao", kana: ["タオ", "タオー", "タォ"] },
  { vi: "thi", kana: ["ティ", "チ"] },
  { vi: "van", kana: ["ヴァン", "バン"] },
  { vi: "tuan", kana: ["トゥアン", "チュアン"] },
  { vi: "tung", kana: ["トゥン", "ツン"] },
  { vi: "tien", kana: ["ティエン", "テン"] },
  { vi: "thien", kana: ["ティエン", "シエン"] },
  { vi: "thuy", kana: ["トゥイ", "スイ", "ティ"] },
  { vi: "thu", kana: ["トゥ", "ツ"] },
  { vi: "trang", kana: ["チャン", "トラン"] },
  { vi: "trinh", kana: ["チン", "トリン"] },
  { vi: "viet", kana: ["ヴィエット", "ビエット"] },
  { vi: "vinh", kana: ["ヴィン", "ビン"] },
  { vi: "yen", kana: ["イエン", "エン"] },
  { vi: "anh", kana: ["アイン", "アン"] },
  { vi: "an", kana: ["アン"] },
  { vi: "bao", kana: ["バオ", "バォ"] },
  { vi: "binh", kana: ["ビン", "ビンー"] },
  { vi: "chien", kana: ["チエン", "チェン"] },
  { vi: "chinh", kana: ["チン", "チィン"] },
  { vi: "cuong", kana: ["クオン", "クオンー", "キュオン"] },
  { vi: "dung", kana: ["ズン", "ドゥン", "ユン"] },
  { vi: "duc", kana: ["ドゥック", "ズック"] },
  { vi: "giang", kana: ["ザン", "ジャン"] },
  { vi: "hai", kana: ["ハイ"] },
  { vi: "hien", kana: ["ヒエン", "ヘン"] },
  { vi: "hoa", kana: ["ホア", "ワ"] },
  { vi: "hoai", kana: ["ホアイ", "ファイ"] },
  { vi: "hong", kana: ["ホン", "フォン"] },
  { vi: "hung", kana: ["フン", "ホン"] },
  { vi: "huy", kana: ["フイ", "フィ", "ヒュイ"] },
  { vi: "phuc", kana: ["フック", "フォック"] },
  { vi: "phuong", kana: ["フオン", "フォン", "ヒョン"] },
  { vi: "quang", kana: ["クアン", "クワン"] },
  { vi: "quoc", kana: ["クオック", "コック"] },
  { vi: "quyen", kana: ["クエン", "クイェン"] },
  { vi: "son", kana: ["ソン"] },
  { vi: "tam", kana: ["タム"] },
  { vi: "tinh", kana: ["ティン", "チン"] },
  { vi: "thang", kana: ["タン", "タング"] },
  { vi: "phat", kana: ["ファット", "フアット"] },
  { vi: "nhung", kana: ["ニュン", "ニョン"] },
  { vi: "ngan", kana: ["ガン", "ンガン"] },
  { vi: "ngocanh", kana: ["ゴックアン", "ンゴックアン"] },
  { vi: "thutrang", kana: ["トゥチャン", "トゥトラン"] },
  { vi: "huong", kana: ["フォン", "フオン", "ホン"] },
  { vi: "uong", kana: ["ウォン", "ウオン", "オン"] },
  { vi: "nguyet", kana: ["グエット", "ングエット"] },
  { vi: "tuyet", kana: ["トゥイェット", "ツイェット"] },
  { vi: "truc", kana: ["チュック", "トゥルック"] },
  { vi: "hanh", kana: ["ハイン", "ハン"] },
  { vi: "han", kana: ["ハン"] },
  { vi: "my", kana: ["ミー", "ミ"] },
  { vi: "nhu", kana: ["ニュ", "ヌ"] },
  { vi: "kieu", kana: ["キエウ", "キョウ"] },
  { vi: "phu", kana: ["フ", "フー"] },
  { vi: "hiep", kana: ["ヒエップ", "ヘップ"] },
  { vi: "quan", kana: ["クアン", "クワン"] },
  { vi: "khan", kana: ["カン"] },
  { vi: "phong", kana: ["フォン", "ホン"] },
  { vi: "huan", kana: ["フアン", "ホアン"] },
  { vi: "thinh", kana: ["ティン", "シン"] },
  { vi: "khue", kana: ["クエ", "フエ"] },
  { vi: "huyen", kana: ["フエン", "ヒュエン"] },
  { vi: "phuoc", kana: ["フオック", "フォック"] },
  { vi: "vietanh", kana: ["ヴィエットアン", "ビエットアン"] },
  { vi: "tu", kana: ["トゥ", "ツ"] },
  { vi: "ngocmai", kana: ["ゴックマイ", "ンゴックマイ"] },
  { vi: "thutruc", kana: ["トゥチュック", "トゥルック"] },
  { vi: "ngoclan", kana: ["ゴックラン", "ンゴックラン"] },
];
